### PR TITLE
Create NFTL

### PR DESCRIPTION
**Pull request by FinanceFR1**
├─ tokens/
│
└─┬─ assets/
  │
  ├─┬─ 0x60781C2586D68229fde47564546784ab3fACA982/
  │   └── logo_48.png

### CODE REVIEW

**Comment by FinanceFR1** [comment]
├─ tokens/
│
└─┬─ assets/
│
├─┬─ 0x60781C2586D68229fde47564546784ab3fACA982/
│   └── logo_48.png

**Comment by bmino** [comment]
Please follow the <https://github.com/pangolindex/tokens#add-yours> instructions in the README

**Comment by FinanceFR1** [comment]
├─ tokens/
│
└─┬─ assets/
  │
  ├─┬─ 0x334c2b4d444010c172c2172e0b1a9a8757f82fcd/
  │ ├── logo_24.png
  │ └── logo_48.png
  │
  ├─┬─ 0x334c2b4d444010c172c2172e0b1a9a8757f82fcd/
  │ ├── logo_24.png
  │ └── logo_48.png
  │
NFTL24 24

 ..
NFTL48 48
.

**Comment by FinanceFR1** [comment]
├─ tokens/
│
└─┬─ assets/
│
├─┬─ 0x334c2b4d444010c172c2172e0b1a9a8757f82fcd/
│ ├──
logo_24 png
 │ └──
logo_48 png

**Comment by bmino** [comment]
closing due to inactivity and incorrect formatting

**Pull request closed without merging**
