### PR TITLE
Adding edbit logos

### PR DESCRIPTION
**Pull request by samo7a**

### CODE REVIEW

**Review by edbitio — APPROVED** [review]
Hi there, please could you review the new logo uploads our developer did. We look forward to immediate approval as our clients are adding liquidation!

Warm regards!

**Review by edbitio — APPROVED** [review]
Hi Pangolin team, I don't mean to be a bother, but I'm loosing clients adding liquidation because of a logo update. Please, please, can you push this into your priority list and update our Logo at the earliest possible. If you have any questions please email me directly at: ridvan@edbit.io. I can also give you my phone number if you'd like to jump on a call.

**Review by nedsa548 — APPROVED** [review]
looking good, approving it rn.

**Comment by edbitio** [comment]
Thank you for the prompt response!
How long does it take for the logo update to reflect here:
https://info.pangolin.exchange/#/token/0x9f3bb52e7c0dffb22a1c7de57eba474b55ccb220

Thanks!

**Comment by nedsa548** [comment]
> Thank you for the prompt response! How long does it take for the logo update to reflect here: https://info.pangolin.exchange/#/token/0x9f3bb52e7c0dffb22a1c7de57eba474b55ccb220
> 
> Thanks!

It'll take a few mins.

**Comment by edbitio** [comment]
It's update now. Much appreciated!

**Pull request merged**
