### PR TITLE
New logos for wagmi

### PR DESCRIPTION
**Pull request by jb1011**
added logos in 24x24 and 48x48 for all wagmi logos

### CODE REVIEW

**Comment by jb1011** [comment]
Adding wagmi logos in 24x24 and 48x48

**Comment by bmino** [comment]
Do these still need to contain `logo.png` as well for legacy support?

**Comment by jb1011** [comment]
We kept the logo.png file because we saw that every folder still had it. But we can update and delete the logo.png file in WAGMI tokens in our PR if you wish

**Comment by jb1011** [comment]
I updated the PR with the new wagmiToken
let me know if I should delete logo.png from our folders

**Review by bmino — APPROVED** [review]

**Pull request merged**
