### PR TITLE
Add EDBIT

### PR DESCRIPTION
**Pull request by samo7a**

### CODE REVIEW

**Comment by samo7a** [comment]
Hello, Can you review this pull request, please?

**Review by edbitio — APPROVED** [review]

**Review by edbitio — APPROVED** [review]
Everything looks good.

**Review by samo7a — COMMENTED** [review]
looks good

**Review by edbitio — APPROVED** [review]
The Pangolin team, please can you update the logo ASAP. This is making us look bad in front of the our clients.

**Comment by HariSeldon23** [comment]
We've moved to a new format. You need to include different size logos but I'll let @nedsa548 comment more

**Comment by edbitio** [comment]
Hi Hari, I have the three logos with the new format:
- logo_24.png
- logo_48.png
- logo.png

How do I create a new pull request as it's not letting me upload the new logos?

**Comment by nedsa548** [comment]
> Hi Hari, I have the three logos with the new format:
> 
> * logo_24.png
> * logo_48.png
> * logo.png
> 
> How do I create a new pull request as it's not letting me upload the new logos?

I'm closing this PR so you can just create a new one.

**Pull request closed without merging**
