### PR TITLE
Avacash.Finance's  token logo

### PR DESCRIPTION
**Pull request by ealyd**
Hello. This is the logo for the $CASH token

The $CASH token is the token for the Avacash.Finance protocol, and it will be used for governance and to share the protocol gains.

More details in the [Tokenomics Article](https://avacash.medium.com/introducing-cash-tokenomics-for-privacy-focused-investments-bbc213a430a0)

About Avacash.Finance: **Privacy-focused Investments in Avalanche**

_Avacash.Finance automatically invest your assets in different DeFi protocols with 100% anonymity improving your privacy by breaking the on-chain link between the recipient and destination addresses of different DeFi assets_

Project Medium: https://avacash.medium.com/
Webpage: https://avacash.finance/
Telegram: https://t.me/AvacashFinance
Twitter: https://twitter.com/AvacashFinance

### CODE REVIEW

**Comment by bmino** [comment]
Please use the checksummed address name as per the README

**Comment by bmino** [comment]
`0xCd426834D733e5B4bFFC89D3f21FA7e16D0Bf583`

**Comment by ealyd** [comment]
> `0xCd426834D733e5B4bFFC89D3f21FA7e16D0Bf583`

Thanks! Now the check-summed address is being used!

**Review by bmino — APPROVED** [review]

**Comment by bmino** [comment]
Good stuff, thanks!

**Pull request merged**
